app:
  - name: message-engine
    properties:
      messages: "停止"
      static: true
      color: [0,0,0,255]
      font:
        family: IPAGothic
        size: 22
  - name: button
    properties:
      label: This is a button.
      color: [255,128,0,255]
      size:
        width: 100
        height: 50
      font:
        family: IPAGothic
        size: 22
