version: 2

jobs:
  build-8_6_3:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: apt update && apt install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev
      - run: cabal new-update
      - restore_cache:
          keys:
            - cabal-index-v1
      - run: cabal new-build
      - run: cabal new-test
      - save_cache:
          key: cabal-index-v1
          paths:
            - ~/.cabal
      - persist_to_workspace:
          root: .
          paths:
            - dist-newstyle
  build-mini-sequencer:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: apt update && apt install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev
      - run: cabal new-update
      - restore_cache:
          keys:
            - cabal-index-v1
      - attach_workspace:
          at: .
      - run: cd examples/mini-sequencer && cabal new-build

workflows:
  version: 2

  # When test has passed, tag a release
  build_and_test:
    jobs:
      - build-8_6_3
      - build-mini-sequencer:
          requires:
            - build-8_6_3
